export enum ActionType {
    SET_NEWSLIST = 'SET_NEWSLIST',
    SET_LOADING_NEWSLIST = 'SET_LOADING_NEWSLIST',
    SET_NEWSCARD = 'SET_NEWSCARD',
    SET_REPLYCOMMENT = 'SET_REPLYCOMMENT',
    UPDATE_REPLYCOMMENT = 'UPDATE_REPLYCOMMENT',
    SET_OPENEDCOMMENTARRAY = "SET_OPENEDCOMMENTARRAY",
    DELETE_NEWSCARD = "DELETE_NEWSCARD",
    DELETE_OPENEDCOMMENTARRAY = "DELETE_OPENEDCOMMENTARRAY"
}